<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ru.anseranser</groupId>
    <artifactId>helpdesk</artifactId>
    <version>1.0</version>
    <name>helpdesk</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>21</maven.compiler.release>
        <yc-sdk-functions.version>2.14.0</yc-sdk-functions.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.yandex.cloud</groupId>
            <artifactId>java-sdk-serverless</artifactId>
            <version>${yc-sdk-functions.version}</version>
        </dependency>
        <dependency>
            <groupId>tech.ydb</groupId>
            <artifactId>ydb-sdk-table</artifactId>
            <version>2.4.9</version>
        </dependency>
        <dependency>
            <groupId>tech.ydb.auth</groupId>
            <artifactId>yc-auth-provider</artifactId>
            <version>2.3.1</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.22.2</version>
        </dependency>
    </dependencies>

    <build>
<!--        <sourceDirectory>${project.basedir}</sourceDirectory>-->
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
